name: Discord Notification

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          message: |
            **Event:** ${{ github.event_name }}
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Actor:** ${{ github.actor }}
            **Commit:** ${{ github.event.head_commit.message }}
            **URL:** ${{ github.event.compare }}
